version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing frontend dependencies...
      - cd frontend
      - npm install

  build:
    commands:
      - echo Building React app...
      - npm run build

  post_build:
    commands:
      - aws s3 sync dist/ s3://$FRONTEND_BUCKET --delete

artifacts:
  files:
    - '**/*'
